version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_freebsd_amd64.zip"
      - "unzip terraform_0.11.14_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - ls -la
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan

  post_build:
    commands:
      - echo terraform plan completed on `date`